import './globals.css'
import type { Metadata } from 'next'
import Providers from "./utils/provider";
import Alerts from '../components/Alert';
import Head from "next/head";
import { Inter } from 'next/font/google'
import { Suspense } from 'react';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Hotels and Co</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          {/* <Alerts /> */}
          <Suspense fallback={<div>Loading page....</div>}>
            {children}
          </Suspense>
           
        </Providers>
       
      </body>
    </html>
  )
}
